services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prod
  #   container_name: gatherly-backend
  #   env_file:
  #     - .env
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  db:
    image: mysql/mysql-server:8.0.21
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=gatherly
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_ROOT_HOST=localhost
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppass"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./docker/db_scripts/mysql:/var/lib/mysql
      - ./docker/db_scripts:/docker-entrypoint-initdb.d
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=pass
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s