services:
  db:
    image: mysql/mysql-server:8.0.21
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=gatherly
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      # - MYSQL_ROOT_HOST=localhost
    ports:
      - '3307:3306'
    volumes:
      - ./docker/db_scripts/mysql:/var/lib/mysql
      - ./docker/db_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=pass
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 3
      start_period: 5s
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: gatherly-backend
    # command: ["npm", "run", "start:dev"]  # Runs your app with file watching
    # command: npm run start:dev
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy