-- AlterTable
ALTER TABLE `post` ADD COLUMN `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `Title` VARCHAR(200) NOT NULL,
    MODIFY `Text` VARCHAR(5000) NOT NULL;

-- CreateTable
CREATE TABLE `PostComment` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `PostId` INTEGER NOT NULL,
    `UserId` INTEGER NOT NULL,
    `Text` VARCHAR(5000) NOT NULL,

    INDEX `Id`(`Id`),
    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PostComment` ADD CONSTRAINT `PostComment_PostId_fkey` FOREIGN KEY (`PostId`) REFERENCES `Post`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PostComment` ADD CONSTRAINT `PostComment_UserId_fkey` FOREIGN KEY (`UserId`) REFERENCES `User`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;
