export const GenerateUserActivityReportUseCaseSymbolProvider = Symbol('GenerateUserActivityReportUseCaseSymbolProvider');
export const GenerateUserActivityReportUseCaseSymbolConsumer = Symbol('GenerateUserActivityReportUseCaseSymbolConsumer');
export const GenerateUserActivityReportUseCaseSymbol = Symbol('GenerateUserActivityReportUseCaseSymbol');
